import streamlit as st


def show_features():

    st.markdown("## ⭐ Why VoyageAI?")

    st.write(
        "Everything you need to plan a memorable trip in one place."
    )

    c1, c2, c3, c4 = st.columns(4)

    with c1:
        st.metric("🤖", "AI Planner")

    with c2:
        st.metric("💰", "Budget")

    with c3:
        st.metric("🍜", "Food")

    with c4:
        st.metric("📍", "Hidden Gems")

    st.write("")

    col1,col2=st.columns(2)

    with col1:

        st.success("Personalized itinerary generated by Gemini AI.")

        st.success("Local restaurants and famous dishes.")

    with col2:

        st.success("Smart budget allocation.")

        st.success("Secret places loved by locals.")

    st.divider()